### ISSUE TITLE
Question: Glob Pattern Support

### ISSUE THREAD

**Issue by aminmeyghani** [roman01la/html-to-react-components#18]
Hi, I was wondering if it's possible to use a glob pattern like this:

```
html2react ./static/**/*.html
```

I have tried it and it only picks up one of the files. I have a feeling it's because of `glob(cli.input[0]...` in `lib/cli.js`.

This is the folder structure that I have:

```
./static/
├── profile
│   ├── profile.css
│   └── profile.html
└── settings
    ├── settings.css
    └── settings.html
```

Thanks!

**Comment by roman01la** [comment]
Hi. I'll look into this when I'll have time. Otherwise I'm happy to merge a PR.

**Comment by aminmeyghani** [comment]
I just made a PR if you could take a look: https://github.com/roman01la/html-to-react-components/pull/19

**Comment by roman01la** [comment]
resolved
