### ISSUE TITLE
Error SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Bombe93** [roman01la/html-to-react-components#21]
Hi,

i'm on Mac and i installed through this command "npm i -g html-to-react-components".

To take a test I took your index.html present in "example" and run this command in the same path "html2react "./*.html" ".

It brings me back this error:

![image](https://user-images.githubusercontent.com/5848941/36037240-71583b06-0dbc-11e8-8260-57d47e0916b7.png)

This error happens to me even when I type only the "html2react" command.
I did a test on Linux and the same thing happens.

**Comment by roman01la** [comment]
Thanks for reporting. I’ll take a look. What version of Node are you running there?

**Comment by Bombe93** [comment]
This on mac:

macos sierra 10.12.6
Node v6.11.4
Npm 5.6.0

**Comment by roman01la** [comment]
Could you try it with Node  v8? I suspect it’s bc of es6 syntax. Can’t verify myself now.

**Comment by aminmeyghani** [comment]
I installed Node v6.12.3 and I can verify that it's happening for me too. Now, the funny thing is when I format the code differently (like add semicolons, remove trailing commas, etc) it parses the file just fine. But then it throws a similar error at `lib/processor.js:85`. My guess is that the parser is different.

**Comment by Bombe93** [comment]
This on Linux Ubuntu:

Ubuntu 17.04
Node 6.11.2
Npm 3.10.10

I'll try with version 8 of node

**Comment by Bombe93** [comment]
I just tried and it worked in this computer:

Ubuntu 17.10
Node v8.9.4
Npm 5.6.0

**Comment by mifan-twan** [comment]
please git it

**Comment by roman01la** [comment]
should be fixed now in v1.6.1
