### ISSUE TITLE
Inline styling leaves out "px" with line-height conversions 

### ISSUE THREAD

**Issue by mandajoan** [roman01la/html-to-react-components#25]
I have ran the converter a few times and noticed it does not convert 'line-height' accurately. 
Instead of converting it as with other styling items such as 'width' or 'align' where the value is placed in quotation marks (ex. "35px"), it converts it to number only and leaves out the size value and quotation marks. It does make the conversion to camel case. 
![html2react-texteditorview](https://user-images.githubusercontent.com/26663739/36332020-350f54ea-1325-11e8-8d2e-58da0a78e9e1.PNG)

example: 
Plain html style:

![html-inline-styling](https://user-images.githubusercontent.com/26663739/36331941-d604c232-1324-11e8-8b30-08bea2bea6a4.png)

same file converted using html-to-react-components

![html2react-inline-styling](https://user-images.githubusercontent.com/26663739/36331958-ed78d05c-1324-11e8-9310-8b7851c6351c.png)

**Comment by roman01la** [comment]
Hi! Just double checked, you are right. Unfortunately HTML to JSX conversion is done by a separate library so there's no an easy way to solve this issue given the amount of all possible cases for CSS values syntax. Let's leave the issue open for now, and I'll add a note into readme. Thanks!

**Comment by roman01la** [comment]
Had a bit of time to dig deeper and looks like it is fixed. Try v1.6.2 :)

**Comment by mandajoan** [comment]
I tried running it (After globally installing 1.6.2) and now I get this error with the react-dom dependency:
![image](https://user-images.githubusercontent.com/26663739/36435392-66dca2ae-1616-11e8-8ea0-95f9558d0976.png)

**Comment by roman01la** [comment]
please try `1.6.3`

**Comment by mandajoan** [comment]
it worked like a charm :) thank you!
