### ISSUE TITLE
Question: Is there way to build unmified browser bundle?

### ISSUE THREAD

**Issue by Aligatro** [roman01la/html-to-react-components#26]
Hello, sorry for the dummy question. It is possible to create human readable in-browser bundle (not minified) of this package? I'am new in webpack and can't handle how to do this.

Thank you.

**Comment by roman01la** [comment]
Curious why do you need this? There's already a script ready for browser usage in `dist` directory.

**Comment by Aligatro** [comment]
На самом деле для отладки, я хочу немного видоизменить функционал и каждый раз пересобирать проект не совсем удобно, да и чтобы в будущем понимать как с этим работать. Гугл к сожалению не дал ответа, как бы я не переписывал конфиг и не отключал флаги при сборке, все-равно на выходе получаю минифицированный бандл.

P.s спасибо за крутую библиотеку.

**Comment by Aligatro** [comment]
Благодарю за потраченное время, вроде со всем разобрался. Просмотрел доки webpack'a и прочёл о окружении и source-map. Еще раз спасибо за либу.
