### ISSUE TITLE
-bash: html2react: command not found

### ISSUE THREAD

**Issue by radityaruben** [roman01la/html-to-react-components#27]
Hi .. i got this msg after installing 
npm i -g html-to-react-components

its installed but somehow i can't access 'html2react' command
+ html-to-react-components@1.6.3
updated 1 package in 22.801s

pls help me .. thx

**Comment by roman01la** [comment]
What OS are you on? How did you install Node?

**Comment by radityaruben** [comment]
I am using Mac .. I downloaded it from nodejs.org to install Node..

![bash error](https://user-images.githubusercontent.com/29673411/37869900-bbdeced4-2ff3-11e8-8b01-28b45ee68bbc.png)

**Comment by Foutchy** [comment]
Same here, on latest of MacOS

**Comment by radityaruben** [comment]
any suggestion?

**Comment by radityaruben** [comment]
Finally work, i just have to reinstall node, but before that i have to delete local lib of all npms folder
