### ISSUE TITLE
Bug: Quotation marks not being converted correctly? Renders as unknown character.

### ISSUE THREAD

**Issue by mandajoan** [roman01la/html-to-react-components#28]
Yesterday I ran code through the package and it was fine, but today it failed to process any of the quotation marks in my html document when converting to react component. I 'm not 100% sure that something on my end didn't set it off, though I am at a loss to what that could have been. Nothing has changed other than some of the html content in the file and the file name, which was updated to reflect the version I am working on. 

This happened with all single and double quotation marks.

![image](https://user-images.githubusercontent.com/26663739/38330008-4cdfc236-3804-11e8-8db5-dc64abe3d26f.png)

**Update:** 

Also failed to convert:

**Ellipses--**

![image](https://user-images.githubusercontent.com/26663739/38330872-98a90dec-3806-11e8-95a1-e417008e5894.png)

**Dash--**

![image](https://user-images.githubusercontent.com/26663739/38330982-e369d032-3806-11e8-982c-bc1a13b82b80.png)

should be:

![image](https://user-images.githubusercontent.com/26663739/38330996-ea8cb8a2-3806-11e8-9cd3-c2d9cb5622e0.png)

**Comment by roman01la** [comment]
Can't really help here, sorry. Could you paste that document here so I can test it on my side?

**Comment by mandajoan** [comment]
I am sorry, I can't post the document because of NDA. But I have run the package twice since I posted the issue and it is still not translating the punctuation correctly.

**Comment by mandajoan** [comment]
I am going to close this as I am not sure if its even an issue with the package. Thank you!
