### ISSUE TITLE
Possible to decide data-components automatically?

### ISSUE THREAD

**Issue by athityakumar** [roman01la/html-to-react-components#37]
First of all, kudos for creating this project! ❤️ 

When dealing with a huge template with multiple pages of HTML content with no annotated `data-components` attribute, would it be possible to automatically decide the components (like, split into very very granular level). I mean, I'd be happier being served LOTs of trivially-small components as the default functionality (ie, when no data-components is specified) rather than ending up with 0 components.

Am I missing something? Is this feature already existent?

**Comment by roman01la** [comment]
This doesn't exist and I don't see how this can be done such that it pleases everyone. If you want on component per DOM node you can run a small script in the browser before copying html that will add data attribute to every DOM node.

**Comment by athityakumar** [comment]
RIght, that'd be my required feature - but as I said, that'd be kinda tedious to execute for a huge template with lots of HTML files. Rather, I feel it'd help to have as default functionality when there's no mention of data-component anywhere. 😅

**Comment by roman01la** [comment]
Default behavior is not gonna change. That said, you can always have a pre pass built elsewhere in user land.

**Comment by athityakumar** [comment]
Ah okay, no problem! 👍
