### ISSUE TITLE
Inline required images are broken

### ISSUE THREAD

**Issue by DavidCasillasRivero** [roman01la/html-to-react-components#38]
When requiring images inline like:

`<img src={require('...')} />` 

The generated output adds quotes around breaking the image.

`<img src="{require('...')}" />`

Is there anyway to support this syntax?

**Comment by roman01la** [comment]
The code is not valid HTML. The tool is made specifically for handling HTML strings.

**Comment by DavidCasillasRivero** [comment]
Yes you are right, I should have catch that myself. I was implementing a tool for converting exported HTML from Google docs into React and I was pre-proccessing the `img` tags before using this tool. I will just swap to proccessing the images after converting to React.
Thanks, excellent tool.
