### ISSUE TITLE
Successfully generated 0 components: 

### ISSUE THREAD

**Issue by parabdeven** [roman01la/html-to-react-components#46]
the command **html2react "./html/index.html"** cannot generate any component
results in message
**Successfully generated 0 components: 
Saved into "components" directory**

**Comment by roman01la** [comment]
Can't help you without an example. A minimal repro would be helpful.

**Comment by vkhobor** [comment]
This happened to me just now. For me it was because I did not add any data-component attributes.

**Comment by roman01la** [comment]
Then it's not an issue. Closing.
