### ISSUE TITLE
Successfully generated 0 components

### ISSUE THREAD

**Issue by asheroto** [roman01la/html-to-react-components#52]
Hello,

I installed the CLI tool and ran it against an HTML file, a directory of HTML files, but it just says...

![image](https://user-images.githubusercontent.com/49938263/107856338-1a3fd600-6ded-11eb-88d7-5162bf27f7fd.png)

I'm on Windows x64 but tried it on my Debian x64 build and got the same result.

Tried Nodejs 14.15.5 and 15,8.0.

**Comment by roman01la** [comment]
Please provide more context,  this is not enough to understand the problem, a repro case would be useful

**Comment by asheroto** [comment]
Sorry, no prob...

I typed a text file with this data

```
<html>
<head>
<title>test</test>
</head>
<body>
<h1>test header</h1>
</body>
</html>
```

and saved it as test.html

I then typed

```
html2react.ps1 test.html
```

and pressed enter, but I get 

![image](https://user-images.githubusercontent.com/49938263/108017688-28534980-6fdb-11eb-8b1d-708a4016d544.png)

Can I just run this command in an empty directory? Or does that change things?

**Comment by roman01la** [comment]
you are not marking any html components, please read the readme and follow instructions

**Comment by asheroto** [comment]
Ha, wow, I have no clue how I didn't see that.  Thanks.
