### ISSUE TITLE
Successfully generated 0 components after adding data-component argument

### ISSUE THREAD

**Issue by Nylakyt5** [roman01la/html-to-react-components#71]
Hi,
I'm looking at your html2react tool and i have an issue regarding the usage.
I have inserted the "data-component" argument to every element present in my index.html, yet when I run :
`html2react <path_to_my_index.html>`

I get this :
`Successfully generated 0 components: 
Saved into "components" directory`

When i try on the sample you provided, it works fine, I'm wondering if I did something wrong here.
I appreciate your help !

**Comment by michaelgthomas** [comment]
> Hi,
> I'm looking at your html2react tool and i have an issue regarding the usage.
> I have inserted the "data-component" argument to every element present in my index.html, yet when I run :
> `html2react <path_to_my_index.html>`
> 
> I get this :
> `Successfully generated 0 components: 
> Saved into "components" directory`
> 
> When i try on the sample you provided, it works fine, I'm wondering if I did something wrong here.
> I appreciate your help !

@Nylakyt5 I've been able to use this previously with no issues. Could you possibly share your HTML?

**Comment by Nylakyt5** [comment]
I'll share a bit of it :

`
<!DOCTYPE html>
<html>
<head data-component="Head">
    <title data-component="Title">Diagram Designer for BIMFM</title>
    <meta charset="utf-8" data-component="Charset">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" data-component="HttpEquiv">
    <meta name="Description" content="diagrams.net is free online diagram software for making flowcharts, process diagrams, org charts, UML, ER and network diagrams" data-component="Description">
    <meta name="Keywords" content="diagram, online, flow chart, flowchart maker, uml, erd" data-component="Keywords">
    <meta itemprop="name" content="diagrams.net - free flowchart maker and diagrams online" data-component="ItemPropName">
	<meta itemprop="description" content="diagrams.net is a free online diagramming application  and flowchart maker . You can use it to create UML, entity relationship,
		org charts, BPMN and BPM, database schema and networks. Also possible are telecommunication network, workflow, flowcharts, maps overlays and GIS, electronic 
		circuit and social network diagrams." data-component="ItemPropDesc">
	<meta itemprop="image" content="https://lh4.googleusercontent.com/-cLKEldMbT_E/Tx8qXDuw6eI/AAAAAAAAAAs/Ke0pnlk8Gpg/w500-h344-k/BPMN%2Bdiagram%2Brc2f.png" data-component="ItempropImg">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" data-component="Viewport">
	<meta name="msapplication-config" content="images/browserconfig.xml" data-component="MSConfig">
    <meta name="mobile-web-app-capable" content="yes" data-component="MobAppAble">
	<meta name="theme-color" content="#d89000" data-component="ThemeColor">
	<script type="text/javascript" data-component="SetupScript">
		// Script that checks if the App is ready to start
	</script>
    <link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/plgmlhohecdddhbmmkncjdmlhcmaachm" data-component="ChrWebItem">
	<link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png" data-component="AppTouchIcon">
	<link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png" data-component="IconTxT">
	<link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png" data-component="IconSxS">
	<link rel="mask-icon" href="images/safari-pinned-tab.svg" color="#d89000" data-component="MaskIcon">
    <link rel="stylesheet" type="text/css" href="styles/grapheditor.css" data-component="Stylesheet">
    <link rel="preconnect" href="https://storage.googleapis.com" data-component="Preconnect">
    <link rel="canonical" href="https://app.diagrams.net" data-component="CanonRef">
	<link rel="manifest" href="images/manifest.json" data-component="Manifest">
	<link rel="shortcut icon" href="favicon.ico" data-component="ShortIcon">
	<style type="text/css" data-component="AppStyle">
		// Styling of the app
	</style>
	
	
		<script type="text/vbscript" data-component="IEScript">
			Function mxUtilsBinaryToArray(Binary)
				Dim i
				ReDim byteArray(LenB(Binary))
				For i = 1 To LenB(Binary)
					byteArray(i-1) = AscB(MidB(Binary, i, 1))
				Next
				mxUtilsBinaryToArray = byteArray
			End Function
		</script>
	
</head>
<body class="geEditor" data-component="geEditor">
	<div id="geInfo" data-component="geInfo">
		<div class="geBlock" data-component="geBlock">
			<h1 data-component="Header">Diagram Designer for BIMFM</h1>
			<p data-component="Paragraph">
				this is a software that allows you to create different diagrams. You can use it as a flowchart maker, network diagram software, to create UML online, as an ER diagram tool, 
				to design database schema, to build BPMN online, as a circuit diagram maker, and more. draw.io can import .vsdx, Gliffy&trade; and Lucidchart&trade; files .
			</p>
			<h2 id="geStatus" data-component="geStatus">Loading...</h2>
			<p data-component="CheckJavaScript"> 
				Please ensure JavaScript is enabled.
			</p>
		</div>
	</div>
	<script type="text/javascript" data-component="StartingScript">
		// Script that starts the app
	</script>
</body>
</html>`

You can see i've added `data-component` to pretty mush every bloc of my index, but no components are actually created.
So, maybe too much components for the command to read ?
